version: '3.8'
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: worksheet
    ports:
    - "5432:5432"
    volumes:
    - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5

  adminer:
    image: adminer
    container_name: adminer
    ports:
    - "8081:8080"
    depends_on:
    - postgres

  keycloak:
    image: quay.io/keycloak/keycloak:21.1.1
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres:5432/worksheet
      KC_DB_USERNAME: postgres
      KC_DB_PASSWORD: root
      KC_HOSTNAME: localhost
      KC_PROXY: edge
      KC_HTTP_ENABLED: "true"
    ports:
    - "8080:8080"
    - "8443:8443"
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
    - ./keycloak-themes:/opt/keycloak/themes
    command: [ "start-dev" ]

volumes:
  pgdata:
