services:
  postgres:
    image: postgres:14
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: yourpassword
      POSTGRES_DB: workday_tracker
    ports:
    - "5432:5432"
    volumes:
    - pgdata:/var/lib/postgresql/data

  backend:
    build: ./backend
    ports:
    - "3001:3000"
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: yourpassword
      DB_NAME: workday_tracker
      JWT_SECRET: your_secret_key
    depends_on:
    - postgres

volumes:
  pgdata:
