name: Worksheet-stack
services:
  db:
    image: postgres:latest
    container_name: postgres-db
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: worksheet
    ports:
    - "5432:5432"

  adminer:
    image: adminer
    container_name: adminer
    ports:
    - "8081:8080"
    depends_on:
    - db

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
    - "8080:8080"
    volumes:
    - ./keycloak-themes:/opt/keycloak/themes
    command: [ "start-dev" ]
